name: 'Base Setup'
inputs:
  jf_username:
    required: true
  jf_password:
    required: true
  ia_ds_bot_app_pem:
    required: true
  ia_ds_bot_app_id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'maven'

    - name: Request a temporary token for "ia-ds-bot"
      id: ia_ds_bot_token
      uses: machine-learning-apps/actions-app-token@0.21
      with:
        APP_PEM: ${{ inputs.ia_ds_bot_app_pem }}
        APP_ID: ${{ inputs.ia_ds_bot_app_id }}

    - name: Save the ia-ds-bot token in the current workflow's environment inside IA_DS_BOT_TOKEN variable
      run: echo "IA_DS_BOT_TOKEN=${{ steps.ia_ds_bot_token.outputs.app_token }}" >> $GITHUB_ENV
      shell: bash

    - name: Configure Git user
      run: |
        git config user.email "106329816+ia-ds-bot[bot]@users.noreply.github.com"
        git config user.name "ia-ds-bot[bot]"
      shell: bash

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
          [
            {
              "id": "central",
              "name": "ia-release",
              "url": "https://intacct.jfrog.io/artifactory/ia-release",
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "snapshots",
              "name": "ia-snapshot",
              "url": "https://intacct.jfrog.io/artifactory/ia-snapshot"
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "central",
              "name": "plugins-release",
              "url": "https://intacct.jfrog.io/artifactory/plugins-release",
              "snapshots": {
                "enabled": "false"
              }
            },
            {
              "id": "snapshots",
              "name": "plugins-snapshot",
              "url": "https://intacct.jfrog.io/artifactory/plugins-snapshot"
            }
          ]
        servers: >
          [
            {
               "id": "central",
               "username": "${{ inputs.jf_username }}",
               "password": "${{ inputs.jf_password }}"
            },
            {
               "id": "snapshots",
               "username": "${{ inputs.jf_username }}",
               "password": "${{ inputs.jf_password }}"
            },
            {
               "id": "github",
               "username": "ia-ds-bot[bot]",
               "password": "${{ env.IA_DS_BOT_TOKEN }}"
            }
          ]

    - name: Checkout ia-ds-utils repo
      uses: actions/checkout@v3
      with:
        repository: intacct/ia-ds-utils
        ref: 'main'
        path: .ia-ds-utils
        token: ${{ env.IA_DS_BOT_TOKEN }}
