name: 2. Minor features release
on: [workflow_dispatch]


jobs:
  minor_release:
    # let the job run only on main
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/feature_release_helper.yml
    with:
      release_type: minor
    secrets: inherit

